require: rubocop-rspec

# opt in to new cops
AllCops:
  NewCops: enable

# Increase maximum method length
Metrics/MethodLength: 
  Max: 20

# Disable frozen string literal comment check
Style/FrozenStringLiteralComment:
  Enabled: false

# Disable top-level class documentation comment check
Style/Documentation:
  Enabled: false

# Allow use of numerical digits in variable names
Naming/VariableNumber:
  Enabled: false

# Allow use of Capybara-specific method names
RSpec/Capybara/FeatureMethods:
  Enabled: false

# Increase maximum rspec example length
RSpec/ExampleLength:
  Max: 10

# Don't restrict length of rspec describe blocks
Metrics/BlockLength:
  IgnoredMethods:
    - describe
